image: node:14

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install -D typescript@4.1.2
    - npm install
    - mkdir -p output/static
  artifacts:
    paths:
      - node_modules/

testing_testing:
  stage: test
  script:
    - npm install -D typescript@4.1.2
    - npm install
    - npm test
    - mkdir -p output/static
